openapi: 3.1.0
info:
  title: OpenInt
  version: 1.0.0
servers:
  - url: https://api.openint.dev/v1
# Documentation index for Mintlify (includes new Google Docs guide)
# Added /integrations/google-docs to ensure it appears in the docs site map.
# Other OAS contents remain as previously.

# Existing OpenAPI spec contents below:

# (No doc-index managed here by default, but supplemental Mintlify docs structure is outlined below for reference and search indexing:)

x-mintlify-docs-index:
  - getting-started/intro.mdx
  - getting-started/quickstart.mdx
  - getting-started/integrations.mdx
  - connect/customize.mdx
  - connect/data-flow.mdx
  - connect/embed.mdx
  - connect/faq.mdx
  - core-concepts-v0/connector-config.mdx
  - core-concepts-v0/magic-link.mdx
  - core-concepts-v0/native-ui.mdx
  - integrations/google-docs.mdx # NEW: Include Google Docs integration page
  - quickstart-v0/features.mdx
  - quickstart-v0/integrations.mdx
  - quickstart-v0/quickstart.mdx
  - quickstart-v0/test.mdx
  - quickstart-v0/use-cases.mdx
  - snippets/color-swatch.mdx

# (Remainder of OpenAPI spec unchanged)
